apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    {{- include "qless-cafe.labels" (merge (dict "app" "redis" "component" "cache") $) | nindent 4 }}
spec:
  selector:
    {{- include "qless-cafe.selectorLabels" (dict "app" "redis" "component" "cache") | nindent 4 }}
  ports:
    - name: redis
      port: 6379
      targetPort: redis
