volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_redis_data: {}


services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: qless_cafe_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: qless_cafe_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/18/docker
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: docker.io/redis:8.0

    volumes:
      - production_redis_data:/data

  celeryworker:
    <<: *django
    image: qless_cafe_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: qless_cafe_production_celerybeat
    command: /start-celerybeat
