# Generated by Django 6.0.8 on 2026-08-23 08:58

import django.db.models.deletion
import qless_cafe.orders.models
import uuid
from django.conf import settings
from django.db import migrations, models


def create_order_number_sequence(apps, schema_editor):
    # SQLite (bare local runs) has no sequence objects; _next_order_number()
    # falls back to max()+1 there instead.
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("CREATE SEQUENCE IF NOT EXISTS orders_order_number_seq;")


def drop_order_number_sequence(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("DROP SEQUENCE IF EXISTS orders_order_number_seq;")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(create_order_number_sequence, drop_order_number_sequence),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.PositiveIntegerField(default=qless_cafe.orders.models._next_order_number, editable=False, unique=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('completed', 'Completed')], default='received', max_length=20)),
                ('pickup_preference', models.CharField(choices=[('asap', 'ASAP'), ('in_10', 'In 10 min'), ('in_20', 'In 20 min')], default='asap', max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=150)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('modifiers_label', models.CharField(blank=True, max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product')),
            ],
        ),
    ]
